<?php

namespace App\DTOs;

class SupplierData
{
    public function __construct(
        public readonly string $name,
        public readonly ?string $legal_name,
        public readonly ?string $trade_name,
        public readonly ?string $supplier_type,
        public readonly ?string $registration_number,
        public readonly ?string $tax_id,
        public readonly ?string $website,
        public readonly ?string $industry,
        public readonly ?string $contact_person,
        public readonly ?string $email,
        public readonly ?string $accounts_email,
        public readonly ?string $purchase_email,
        public readonly ?string $phone,
        public readonly ?string $alternate_phone,
        public readonly ?string $address,
        public readonly ?string $address_line_1,
        public readonly ?string $address_line_2,
        public readonly ?string $city,
        public readonly ?string $state,
        public readonly ?string $postal_code,
        public readonly ?string $country,
        public readonly ?string $bank_name,
        public readonly ?string $bank_branch,
        public readonly ?string $account_name,
        public readonly ?string $account_number,
        public readonly ?string $account_type,
        public readonly ?string $ifsc_code,
        public readonly ?string $swift_bic,
        public readonly ?string $beneficiary_name,
        public readonly ?string $bank_country,
        public readonly ?string $blank_cheque_path,
        public readonly ?string $gst_document_path,
        public readonly string $status,
        public readonly array $company_ids,
        public readonly ?string $notes,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            name: $data['name'],
            legal_name: empty($data['legal_name']) ? null : $data['legal_name'],
            trade_name: empty($data['trade_name']) ? null : $data['trade_name'],
            supplier_type: empty($data['supplier_type']) ? null : $data['supplier_type'],
            registration_number: empty($data['registration_number']) ? null : $data['registration_number'],
            tax_id: empty($data['tax_id']) ? null : $data['tax_id'],
            website: empty($data['website']) ? null : $data['website'],
            industry: empty($data['industry']) ? null : $data['industry'],
            contact_person: empty($data['contact_person']) ? null : $data['contact_person'],
            email: empty($data['email']) ? null : $data['email'],
            accounts_email: empty($data['accounts_email']) ? null : $data['accounts_email'],
            purchase_email: empty($data['purchase_email']) ? null : $data['purchase_email'],
            phone: normalize_indian_phone($data['phone'] ?? null),
            alternate_phone: normalize_indian_phone($data['alternate_phone'] ?? null),
            address: empty($data['address']) ? null : $data['address'],
            address_line_1: empty($data['address_line_1']) ? null : $data['address_line_1'],
            address_line_2: empty($data['address_line_2']) ? null : $data['address_line_2'],
            city: empty($data['city']) ? null : $data['city'],
            state: empty($data['state']) ? null : $data['state'],
            postal_code: empty($data['postal_code']) ? null : $data['postal_code'],
            country: empty($data['country']) ? null : $data['country'],
            bank_name: empty($data['bank_name']) ? null : $data['bank_name'],
            bank_branch: empty($data['bank_branch']) ? null : $data['bank_branch'],
            account_name: empty($data['account_name']) ? null : $data['account_name'],
            account_number: empty($data['account_number']) ? null : $data['account_number'],
            account_type: empty($data['account_type']) ? null : $data['account_type'],
            ifsc_code: empty($data['ifsc_code']) ? null : $data['ifsc_code'],
            swift_bic: empty($data['swift_bic']) ? null : $data['swift_bic'],
            beneficiary_name: empty($data['beneficiary_name']) ? null : $data['beneficiary_name'],
            bank_country: empty($data['bank_country']) ? null : $data['bank_country'],
            blank_cheque_path: empty($data['blank_cheque_path']) ? null : $data['blank_cheque_path'],
            gst_document_path: empty($data['gst_document_path']) ? null : $data['gst_document_path'],
            status: $data['status'] ?? 'active',
            company_ids: $data['company_ids'] ?? [],
            notes: empty($data['notes']) ? null : $data['notes'],
        );
    }

    public function toArray(): array
    {
        return [
            'name' => $this->name,
            'legal_name' => $this->legal_name,
            'trade_name' => $this->trade_name,
            'supplier_type' => $this->supplier_type,
            'registration_number' => $this->registration_number,
            'tax_id' => $this->tax_id,
            'website' => $this->website,
            'industry' => $this->industry,
            'contact_person' => $this->contact_person,
            'email' => $this->email,
            'accounts_email' => $this->accounts_email,
            'purchase_email' => $this->purchase_email,
            'phone' => $this->phone,
            'alternate_phone' => $this->alternate_phone,
            'address' => $this->address,
            'address_line_1' => $this->address_line_1,
            'address_line_2' => $this->address_line_2,
            'city' => $this->city,
            'state' => $this->state,
            'postal_code' => $this->postal_code,
            'country' => $this->country,
            'bank_name' => $this->bank_name,
            'bank_branch' => $this->bank_branch,
            'account_name' => $this->account_name,
            'account_number' => $this->account_number,
            'account_type' => $this->account_type,
            'ifsc_code' => $this->ifsc_code,
            'swift_bic' => $this->swift_bic,
            'beneficiary_name' => $this->beneficiary_name,
            'bank_country' => $this->bank_country,
            'blank_cheque_path' => $this->blank_cheque_path,
            'gst_document_path' => $this->gst_document_path,
            'status' => $this->status,
            'company_ids' => $this->company_ids,
            'notes' => $this->notes,
        ];
    }
}
