<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>{{ $supplier->name }} - Vendor Profile</title>
<style>
@page{margin:30px 34px 44px}body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:10px;line-height:1.5}.header{background:#173b68;color:white;padding:24px;border-radius:8px}.header h1{font-size:24px;margin:0 0 4px}.header p{margin:0;color:#dbeafe}.section{margin-top:16px;page-break-inside:avoid}.section h2{font-size:11px;text-transform:uppercase;color:#173b68;background:#eaf1f8;border-left:4px solid #2d6da3;padding:7px 9px;margin:0 0 8px}table{width:100%;border-collapse:collapse}td,th{padding:7px 8px;border:1px solid #dce3ea;text-align:left;vertical-align:top}th{font-size:8px;text-transform:uppercase;color:#64748b;background:#f5f7fa}.label{font-size:8px;text-transform:uppercase;color:#64748b}.value{font-weight:bold;margin-top:2px}.footer{position:fixed;bottom:-28px;left:0;right:0;text-align:center;color:#7b8794;font-size:8px}.badge{display:inline-block;background:#e8f1fb;color:#173b68;padding:3px 8px;border-radius:9px}.muted{color:#7b8794}
</style></head><body>
<div class="footer">Vendor profile generated {{ now()->format('d M Y, h:i A') }} - Account numbers are shown in full</div>
<div class="header"><h1>{{ $supplier->name }}</h1><p>{{ $supplier->legal_name ?: 'Supplier / Vendor Profile' }}</p></div>
<div class="section"><h2>Business Details</h2><table>
<tr><td><div class="label">Trade Name</div><div class="value">{{ $supplier->trade_name ?: '-' }}</div></td><td><div class="label">Supplier Type</div><div class="value">{{ $supplier->supplier_type ?: '-' }}</div></td><td><div class="label">Industry</div><div class="value">{{ $supplier->industry ?: '-' }}</div></td><td><div class="label">Status</div><div class="value"><span class="badge">{{ Str::title($supplier->status) }}</span></div></td></tr>
<tr><td><div class="label">Registration Number</div><div class="value">{{ $supplier->registration_number ?: '-' }}</div></td><td><div class="label">GST / Tax ID</div><div class="value">{{ $supplier->tax_id ?: '-' }}</div></td><td colspan="2"><div class="label">Website</div><div class="value">{{ $supplier->website ?: '-' }}</div></td></tr></table></div>
<div class="section"><h2>Contact Details</h2><table><tr><th>Contact Person</th><th>Email</th><th>Phone 1</th><th>Phone 2</th></tr><tr><td>{{ $supplier->contact_person ?: '-' }}</td><td>{{ $supplier->email ?: '-' }}</td><td>{{ $supplier->phone ?: '-' }}</td><td>{{ $supplier->alternate_phone ?: '-' }}</td></tr></table></div>
<div class="section"><h2>Address</h2><table><tr><td>{{ collect([$supplier->address_line_1,$supplier->address_line_2,$supplier->city,$supplier->state,$supplier->postal_code,$supplier->country])->filter()->join(', ') ?: ($supplier->address ?: '-') }}</td></tr></table></div>
<div class="section"><h2>Brands / Companies Supplied</h2><table><thead><tr><th>Code</th><th>Brand / Company</th><th>Status</th></tr></thead><tbody>@forelse($supplier->companies as $company)<tr><td>{{ $company->company_code }}</td><td>{{ $company->short_name ?: $company->company_name }}</td><td>{{ Str::title($company->status) }}</td></tr>@empty<tr><td colspan="3" class="muted">No brands or companies assigned.</td></tr>@endforelse</tbody></table></div>
<div class="section"><h2>Bank Details</h2><table><tr><th>Bank</th><th>Branch</th><th>Account</th><th>Type</th></tr><tr><td>{{ $supplier->bank_name ?: '-' }}</td><td>{{ $supplier->bank_branch ?: '-' }}</td><td>{{ $supplier->full_account_number ?: '-' }}</td><td>{{ $supplier->account_type ?: '-' }}</td></tr><tr><th>IFSC</th><th>SWIFT / BIC</th><th colspan="2">Beneficiary</th></tr><tr><td>{{ $supplier->ifsc_code ?: '-' }}</td><td>{{ $supplier->swift_bic ?: '-' }}</td><td colspan="2">{{ $supplier->beneficiary_name ?: '-' }}</td></tr></table></div>
<div class="section"><h2>Notes & Record Information</h2><table><tr><td>{{ $supplier->notes ?: 'No notes.' }}</td></tr><tr><td class="muted">Created {{ $supplier->created_at?->format('d M Y, h:i A') }} · Updated {{ $supplier->updated_at?->format('d M Y, h:i A') }}</td></tr></table></div>
</body></html>
